#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1364478486.477711
__CHEETAH_genTimestamp__ = 'Thu Mar 28 21:48:06 2013'
__CHEETAH_src__ = 'PL0_H.tmpl'
__CHEETAH_srcLastModified__ = 'Thu Mar 28 21:48:04 2013'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class PL0_H(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(PL0_H, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''#ifndef ''')
        _v = VFFSL(SL,"header.name",True) # u'$header.name' on line 1, col 9
        if _v is not None: write(_filter(_v, rawExpr=u'$header.name')) # from line 1, col 9.
        write(u'''
#define ''')
        _v = VFFSL(SL,"header.name",True) # u'$header.name' on line 2, col 9
        if _v is not None: write(_filter(_v, rawExpr=u'$header.name')) # from line 2, col 9.
        write(u'''

/* Macro definition */
''')
        for macro in VFFSL(SL,"macros",True): # generated from line 5, col 1
            write(u'''#define ''')
            _v = VFFSL(SL,"macro.name",True) # u'$macro.name' on line 6, col 9
            if _v is not None: write(_filter(_v, rawExpr=u'$macro.name')) # from line 6, col 9.
            write(u''' ''')
            _v = VFFSL(SL,"macro.value",True) # u'$macro.value' on line 6, col 21
            if _v is not None: write(_filter(_v, rawExpr=u'$macro.value')) # from line 6, col 21.
            write(u'''
''')
        write(u'''
/* enum definition */
''')
        for enum in VFFSL(SL,"enums",True): # generated from line 10, col 1
            write(u'''enum ''')
            _v = VFFSL(SL,"enum.name",True) # u'$enum.name' on line 11, col 6
            if _v is not None: write(_filter(_v, rawExpr=u'$enum.name')) # from line 11, col 6.
            write(u''' {
''')
            for enum_value in VFFSL(SL,"enum.values",True): # generated from line 12, col 1
                write(u'''     ''')
                _v = VFFSL(SL,"enum_value",True) # u'$enum_value' on line 13, col 6
                if _v is not None: write(_filter(_v, rawExpr=u'$enum_value')) # from line 13, col 6.
                write(u''',
''')
            write(u'''};
''')
        write(u'''
/* struct definition */
''')
        for struct in VFFSL(SL,"structs",True): # generated from line 19, col 1
            write(u'''typedef struct {
''')
            for item in VFFSL(SL,"struct.items",True): # generated from line 21, col 1
                write(u'''     ''')
                _v = VFFSL(SL,"item.type",True) # u'$item.type' on line 22, col 6
                if _v is not None: write(_filter(_v, rawExpr=u'$item.type')) # from line 22, col 6.
                write(u''' ''')
                _v = VFFSL(SL,"item.name",True) # u'$item.name' on line 22, col 17
                if _v is not None: write(_filter(_v, rawExpr=u'$item.name')) # from line 22, col 17.
                write(u''';
''')
            write(u'''} ''')
            _v = VFFSL(SL,"struct.name",True) # u'$struct.name' on line 24, col 3
            if _v is not None: write(_filter(_v, rawExpr=u'$struct.name')) # from line 24, col 3.
            write(u''';
''')
        write(u'''
/* global variable definition */
''')
        for variable in VFFSL(SL,"variables",True): # generated from line 28, col 1
            _v = VFFSL(SL,"variable.type",True) # u'$variable.type' on line 29, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$variable.type')) # from line 29, col 1.
            write(u''' ''')
            _v = VFFSL(SL,"variable.name",True) # u'$variable.name' on line 29, col 16
            if _v is not None: write(_filter(_v, rawExpr=u'$variable.name')) # from line 29, col 16.
            write(u''';
''')
        write(u'''
/* function definition */
''')
        for function in VFFSL(SL,"functions",True): # generated from line 33, col 1
            _v = VFFSL(SL,"function.return_type",True) # u'$function.return_type' on line 34, col 1
            if _v is not None: write(_filter(_v, rawExpr=u'$function.return_type')) # from line 34, col 1.
            write(u''' ''')
            _v = VFFSL(SL,"function.name",True) # u'$function.name' on line 34, col 23
            if _v is not None: write(_filter(_v, rawExpr=u'$function.name')) # from line 34, col 23.
            write(u''';
''')
        write(u'''
#endif''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_PL0_H= 'respond'

## END CLASS DEFINITION

if not hasattr(PL0_H, '_initCheetahAttributes'):
    templateAPIClass = getattr(PL0_H, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(PL0_H)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=PL0_H()).run()


